/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gitflow.test;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
 	
	String greeting = new App().getGreeting();

	for(int i = 0; i < greeting.size(); i++){
		System.out.println(greeting);
	}
    }
}
